# Starship prompt configuration
# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Prompt format
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$singularity\
$kubernetes\
$container\
$docker_context\
$direnv\
$env_var\
$custom\
$line_break\
$jobs\
$status\
$character"""

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[git_branch]
symbol = ''
